apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    app: demo-app
  name: demo-app
spec:
  containers:
  - image: demo-application:latest
    imagePullPolicy: Never
    name: demo-app
    resources: {}
    env:
    - name: DBSERVICE
      value: "demo-db-service.default.svc.cluster.local"
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
